Add dex contracts
gnosis/dex-js pull request #2
Opened 2019-11-26 17:29 UTC by anxolin

Adds dex-contracts. 

Additionally it creates a simple file to get the ABI and print the methods of the SC. Run it with:
`yarn sandbox test/sandbox/contracts/getAbi.ts`

2019-11-26 17:41 UTC, alfetopito approved these changes

2019-11-27 10:00 UTC, Velenir requested changes

2019-11-27 10:00 UTC, Velenir commented on test/sandbox/contracts/getAbi.ts
> +import StablecoinConverter from '@gnosis.pm/dex-contracts/build/contracts/StablecoinConverter.json'
Destructure here and everywhere else you don't need a whole json. Webpack and its ilk are smart enough to tree-shake other fields one level deep in json.

2019-11-28 12:15 UTC, Velenir approved these changes

2019-11-28 13:56 UTC, W3stside approved these changes

2019-12-03 14:36 UTC, merged