Update Token List with correct IDs
gnosis/dex-js pull request #89
Opened 2020-02-07 14:21 UTC by bh2smith

Check, via `tokenIdToAddressMap` on etherscan - https://etherscan.io/address/0x6F400810b62df8E13fded51bE75fF5393eaa841F#readContract that the following tokens have the ids as updated here.

Closes #88

2020-02-07 14:26 UTC, anxolin approved these changes
Great catch!

The issue is that we are not getting the id from the smart contract. I believe we need to address this asap to prevent this issues.

This was flagged by Leandro already

2020-02-10 11:03 UTC, alfetopito requested changes
Tiny issue with JSON formating

2020-02-10 11:03 UTC, alfetopito commented on src/tokenList.json
> +  }
Missing a comma

2020-02-10 11:24 UTC, bh2smith commented
My only concern now is that this change will result in OWL being listed first in the dropdown menu on the interface.

2020-02-10 11:25 UTC, alfetopito commented
> My only concern now is that this change will result in OWL being listed first in the dropdown menu on the interface.

You can just move it down the list and keep the id `0`.
AFAIK we don't sort based on id and use instead the array position.

2020-02-10 11:27 UTC, alfetopito approved these changes

2020-02-10 11:37 UTC, merged